export const questions = [
  {
    id: "path-preference",
    question: "Which path calls to your soul for creating your SoulMovie?",
    type: "multiple-choice",
    options: [
      "Guided Questionnaire - I prefer a structured, reflective approach",
      "Quantum Healing Hypnosis Session - I'm drawn to deep hypnotic exploration",
      "I'm not sure yet - I'd like guidance on which path suits me best",
    ],
  },
  {
    id: "current-challenges",
    question: "What life challenges or patterns would you like your SoulMovie to help transform?",
    type: "open-ended",
  },
  {
    id: "spiritual-goals",
    question: "What spiritual or personal growth goals do you hope to achieve?",
    type: "multiple-choice",
    options: [
      "Connect with my Higher Self and inner wisdom",
      "Heal from past traumas or emotional wounds",
      "Discover my life purpose and soul mission",
      "Release limiting beliefs and patterns",
      "Enhance my intuition and spiritual gifts",
      "Find inner peace and emotional balance",
      "Other (please specify in next question)",
    ],
  },
  {
    id: "specific-intentions",
    question: "Are there specific intentions or areas you'd like your SoulMovie to focus on?",
    type: "open-ended",
  },
  {
    id: "meditation-experience",
    question: "What is your experience with meditation and spiritual practices?",
    type: "multiple-choice",
    options: [
      "Complete beginner - new to meditation",
      "Some experience - I meditate occasionally",
      "Regular practitioner - I have an established practice",
      "Advanced - I've explored various spiritual modalities",
      "Professional - I teach or guide others in spiritual practices",
    ],
  },
  {
    id: "hypnosis-comfort",
    question: "How comfortable are you with hypnosis or altered states of consciousness?",
    type: "multiple-choice",
    options: [
      "Very comfortable - I've experienced hypnosis before",
      "Somewhat comfortable - I'm open but haven't tried it",
      "Neutral - I'm curious but have some reservations",
      "Uncomfortable - I prefer to stay in normal consciousness",
      "Not applicable - I'm choosing the questionnaire path",
    ],
  },
  {
    id: "life-themes",
    question: "What themes or symbols frequently appear in your life, dreams, or meditations?",
    type: "open-ended",
  },
  {
    id: "healing-focus",
    question: "Is there a particular area of your life that needs healing or transformation?",
    type: "multiple-choice",
    options: [
      "Relationships and love",
      "Career and life purpose",
      "Health and vitality",
      "Family and ancestral patterns",
      "Self-worth and confidence",
      "Spiritual connection and growth",
      "Financial abundance and security",
      "Creative expression and gifts",
    ],
  },
  {
    id: "energy-sensitivity",
    question: "How sensitive are you to energy, emotions, or spiritual phenomena?",
    type: "multiple-choice",
    options: [
      "Highly sensitive - I easily pick up on energies and emotions",
      "Moderately sensitive - I notice subtle energies sometimes",
      "Somewhat sensitive - I'm becoming more aware",
      "Not very sensitive - I'm more grounded in physical reality",
      "I'm not sure about my sensitivity level",
    ],
  },
  {
    id: "transformation-readiness",
    question: "How ready are you for deep personal transformation and change?",
    type: "multiple-choice",
    options: [
      "Completely ready - I'm prepared for profound shifts",
      "Very ready - I welcome positive changes in my life",
      "Somewhat ready - I'm open but want to go at my own pace",
      "Cautiously ready - I want change but feel some resistance",
      "I'm exploring - still deciding if I'm ready for big changes",
    ],
  },
  {
    id: "soul-calling",
    question: "What does your soul most deeply yearn for right now?",
    type: "open-ended",
  },
  {
    id: "movie-preferences",
    question: "What type of imagery, music, or themes resonate most with your soul?",
    type: "open-ended",
  },
]
